table_names:
  cdmx_df: tabladf
  edomex_df: tablaedomex

cat_month_num:
  enero: "01"
  febrero: "02"
  marzo: "03"
  abril: "04"
  mayo: "05"
  junio: "06"
  julio: "07"
  agosto: "08"
  septiembre: "09"
  octubre: "10"
  noviembre: "11"
  diciembre: "12"

url: "http://www.aire.cdmx.gob.mx/ultima-hora-reporte.php"

headers:
  User-Agent: "Mozilla/5.0"

proc_log_name: "etl_log.log"